version: '3'

services:
  web:
    build:
      context: .
      target: web-dev

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./docker_data/db/data:/var/lib/postgresql/data:rw

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'dev-mercure-jwt-key'
      MERCURE_SUBSCRIBER_JWT_KEY: 'dev-mercure-jwt-key'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - ./docker_data/mercure/data:/data
      - ./docker_data/mercure/config:/config

####> symfony/mercure-bundle ###
#  mercure:
#    image: dunglas/mercure
#    restart: unless-stopped
#    environment:
#      SERVER_NAME: ':80'
#      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
#      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
#      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
#      MERCURE_EXTRA_DIRECTIVES: |
#        cors_origins http://127.0.0.1:8000
#    # Comment the following line to disable the development mode
#    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
#    volumes:
#      - mercure_data:/data
#      - mercure_config:/config
####< symfony/mercure-bundle ###

volumes:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
