version: '3'

services:
  web:
    build:
      context: .
      target: web-dev

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./docker_data/db/data:/var/lib/postgresql/data:rw

  node:
    image: node:18-alpine
    working_dir: /var/www
